name: Build test
on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: 1.x
      - name: Build check
        run: |
          go build .
      - name: Prepare test
        run: |
          mkdir -p ~/.aws
          echo "[default]
          region = us-west-1
          " > ~/.aws/config

          echo "[default]
          aws_access_key_id = dummy
          aws_secret_access_key = dummy
          " > ~/.aws/credentials
      - name: go test
        run: |
          go test -v ./...
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
